# NUMPY LIBRARIES
#### NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays

In [1]:
import numpy as np

In [2]:
# Array---Data Structure that stores same data type
# This is the main difference between List(That Can Store Multiple Data Type) and Array

In [14]:
# Needs to pass a list to create an array
arr2 = np.array([[15,10,20]])
print(arr2.shape)
arr2

(1, 3)


array([[15, 10, 20]])

In [8]:
type(arr)

numpy.ndarray

In [11]:
arr1 = np.array([15,10,20])
print(arr1.shape)

(3,)


In [35]:
### Multinested array
L1 = [1,2,3,4,5]
L2 = [6,7,8,9,10]
L3 = [11,92,13,14,15]

In [47]:
MA = np.array([L1,L2,L3])
print(MA)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 92 13 14 15]]


In [18]:
MA.shape

(3, 5)

In [20]:
MA.ndim

2

In [22]:
X=MA.tolist()

In [25]:
X[0]

[1, 2, 3, 4, 5]

In [26]:
X[1]

[6, 7, 8, 9, 10]

In [27]:
X[2]

[11, 12, 13, 14, 15]

In [54]:
MA.argmax()

11

In [29]:
MA.view()

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
MA.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [31]:
MA.sum()

120

In [32]:
MA.all()

True

In [33]:
MA.any()

True

In [37]:
MA.argsort()

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 2, 3, 4, 1]], dtype=int64)

In [39]:
MA.astype('object')

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 10],
       [11, 92, 13, 14, 15]], dtype=object)

In [49]:
MA.shape

(3, 5)

In [52]:
print(MA)
print(MA.ndim)
print(MA.reshape(5,3))


[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 92 13 14 15]]
2
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 92]
 [13 14 15]]


### INDEXING IN NUMPY ARRAY
##### First row, Then Columns,
##### Better to say ar[ListNo]

In [55]:
ar = np.array([5,10,16,20,26])

In [57]:
ar[1:6]

array([10, 16, 20, 26])

In [65]:
ar2 = np.array([[3,6,9,12,15],[2,4,6,8,10],[5,10,15,2,0],[9,8,66,55,44]])
ar2

array([[ 3,  6,  9, 12, 15],
       [ 2,  4,  6,  8, 10],
       [ 5, 10, 15,  2,  0],
       [ 9,  8, 66, 55, 44]])

In [66]:
ar2[:,:]

array([[ 3,  6,  9, 12, 15],
       [ 2,  4,  6,  8, 10],
       [ 5, 10, 15,  2,  0],
       [ 9,  8, 66, 55, 44]])

In [67]:
ar2[:,1:3]

array([[ 6,  9],
       [ 4,  6],
       [10, 15],
       [ 8, 66]])

In [68]:
ar2[2:,1:3]

array([[10, 15],
       [ 8, 66]])

In [69]:
ar2[1]

array([ 2,  4,  6,  8, 10])

In [75]:
np.arange(10,20,5)

array([10, 15])

In [78]:
A=np.linspace(10,20,5)
A

array([10. , 12.5, 15. , 17.5, 20. ])

In [80]:
A[2:]=200
A

array([ 10. ,  12.5, 200. , 200. , 200. ])

In [81]:
ar2

array([[ 3,  6,  9, 12, 15],
       [ 2,  4,  6,  8, 10],
       [ 5, 10, 15,  2,  0],
       [ 9,  8, 66, 55, 44]])

In [83]:
ar2%2==0

array([[False,  True, False,  True, False],
       [ True,  True,  True,  True,  True],
       [False,  True, False,  True,  True],
       [False,  True,  True, False,  True]])

In [85]:
#coditioonal access, like DataFrame
ar2[ar2%2==0]

array([ 6, 12,  2,  4,  6,  8, 10, 10,  2,  0,  8, 66, 44])

In [86]:
np.ones(5,)

array([1., 1., 1., 1., 1.])

In [88]:
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [89]:
#random distribution
np.random.rand(3,3)

array([[0.44767113, 0.22028268, 0.93253066],
       [0.28264726, 0.41203138, 0.16841519],
       [0.7311384 , 0.15720924, 0.61280177]])

In [90]:
#
np.random.randn(4,4)

array([[-0.66067412, -0.66843967, -0.06883899, -0.7181389 ],
       [ 0.29272083, -0.63255086, -0.78895138, -1.55972756],
       [ 0.64078012,  1.1289392 , -0.22786894,  0.88356551],
       [ 0.58915214, -0.70730673, -0.7172691 ,  1.4283386 ]])

In [94]:
np.random.randint(50,100,size=5)

array([96, 92, 59, 65, 99])

In [103]:
# an array between 0 to 1
np.random.rand(5,2)

array([[0.43555382, 0.64161031],
       [0.51738557, 0.29884153],
       [0.92344301, 0.37607649],
       [0.70153572, 0.98184369],
       [0.29456963, 0.65997512]])

In [97]:
np.random.random_integers(10,50,5)

C:\Users\tiken\anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: This function is deprecated. Please call randint(10, 50 + 1) instead
  """Entry point for launching an IPython kernel.


array([14, 44, 24, 34, 43])

In [101]:
# Randm integer from a range
np.random.randint(10,50,5)

array([37, 33, 43, 17, 39])

In [100]:
#random normal distribution
np.random.randn(5,5) 

array([[-1.63891541e-01, -2.09825551e-01, -3.45673360e-01,
        -1.99880325e+00, -1.21041920e+00],
       [ 2.87689570e-01, -1.59563092e+00,  7.54572094e-01,
        -9.80241376e-01,  1.80082557e+00],
       [-1.62185404e-01, -1.84473270e-03,  8.42165359e-01,
         2.85727781e-02,  8.06663821e-01],
       [ 9.46625456e-01,  1.68086968e+00,  5.66546721e-02,
         2.61435996e-02, -1.48136859e+00],
       [ 7.01960569e-01,  1.18441106e+00, -3.83440035e-01,
        -1.78803999e-01, -5.73832990e-01]])

In [104]:
np.random.rand(1,10)

array([[0.58521709, 0.98334551, 0.17145245, 0.00599425, 0.71318791,
        0.60693093, 0.5343119 , 0.81337733, 0.29615334, 0.98482361]])

In [113]:
np.random.randn(1,10)

array([[-1.47139419,  1.49636638, -1.97530725, -0.96846863,  1.69500744,
        -1.81801643,  1.54745788,  1.1484247 , -1.61826108,  0.6237312 ]])

In [118]:
A = np.random.randint(5,10,20)
print(A)
B = np.random.random(45)
print(B)

[6 9 9 5 7 6 7 5 5 5 7 8 5 6 9 6 8 8 5 6]
[0.09855912 0.54170793 0.29048583 0.25139785 0.7724482  0.3239978
 0.79994125 0.32724962 0.6400405  0.08310489 0.83688226 0.60388727
 0.01372807 0.43092812 0.00160268 0.48884994 0.17959276 0.96910056
 0.85516743 0.28019791 0.45183119 0.5340901  0.33002755 0.75522133
 0.97960747 0.72947336 0.39305257 0.14839835 0.75356048 0.92918032
 0.6824151  0.62856857 0.83853052 0.67015035 0.12581195 0.64314326
 0.50899    0.19985284 0.24447067 0.60195385 0.72341625 0.28233834
 0.88118195 0.74538618 0.48118622]


In [119]:
A = np.random.randint(5,10,20)
print(A)
A1 = np.linspace(5,10,20)
print(A1)

[7 8 8 8 8 7 6 5 5 9 7 8 8 6 5 8 9 8 6 9]
[ 5.          5.26315789  5.52631579  5.78947368  6.05263158  6.31578947
  6.57894737  6.84210526  7.10526316  7.36842105  7.63157895  7.89473684
  8.15789474  8.42105263  8.68421053  8.94736842  9.21052632  9.47368421
  9.73684211 10.        ]


In [121]:
A2 = np.random.randint(5,100,20)
print(A2)
A2.reshape(5,4)

[61 93 25 32 53 94 22 63 30 80 33 77 73 82 33 14 47 73 44 69]


array([[61, 93, 25, 32],
       [53, 94, 22, 63],
       [30, 80, 33, 77],
       [73, 82, 33, 14],
       [47, 73, 44, 69]])