In [1]:
import pandas as pd
import numpy as np

In [2]:
x1=np.random.randint(low=1,high=20,size=(50,))

x2=np.random.randint(low=1,high=20,size=(50,))

In [3]:
#np.random.seed(67)
y=3+2*x1-4*x2+np.random.random((50,))

In [4]:
y

array([ 21.55165203,  -4.64177701, -14.04580854, -36.12773817,
       -10.86250697,   7.36430162,  -2.29346629,  17.82415468,
       -32.51427243, -20.32056524, -16.00136838,   3.20853546,
       -30.62131596, -12.00699686, -24.95640904,  -6.88795828,
         7.08616044,   5.49794465,  -6.5195045 , -28.44970552,
       -52.79832297, -26.47156254, -20.58859072, -36.86368021,
       -46.08449259,  -2.71248177,  -0.23081482, -40.01170657,
       -54.74316476,  -0.71361034, -34.18811263, -28.01018423,
       -32.30369556, -44.87878408, -48.27605498,  17.40501492,
        13.15676679,  23.98423859,   3.54044732, -16.82929318,
       -12.77021077, -38.35612905,  -2.25225043,  -6.81177518,
        23.30945984, -34.09122584,  -8.9274212 , -48.68721313,
         5.58368429,  -6.49177393])

In [5]:
x1

array([13, 12, 19, 18, 19, 10, 17,  9,  4,  8,  8,  8, 15, 10, 14,  7,  8,
       13,  5,  8,  4, 15, 12, 10, 11, 17, 14, 16,  9, 14,  7,  6,  4,  4,
        8, 13,  9, 18, 10,  4, 18,  1,  7, 13, 14,  1, 18,  4,  9, 17])

In [6]:
x2

array([ 2,  8, 14, 19, 13,  4, 10,  1, 11, 10,  9,  4, 16,  9, 14,  6,  3,
        6,  5, 12, 16, 15, 12, 15, 18, 10,  8, 19, 19,  8, 13, 11, 11, 14,
       17,  3,  2,  4,  5,  7, 13, 11,  5,  9,  2, 10, 12, 15,  4, 11])

In [7]:

x=pd.DataFrame({'intercept':np.ones_like(x1),'x1':x1,'x2':x2})
x


intercept  x1  x2
0           1  13   2
1           1  12   8
2           1  19  14
3           1  18  19
4           1  19  13
5           1  10   4
6           1  17  10
7           1   9   1
8           1   4  11
9           1   8  10
10          1   8   9
11          1   8   4
12          1  15  16
13          1  10   9
14          1  14  14
15          1   7   6
16          1   8   3
17          1  13   6
18          1   5   5
19          1   8  12
20          1   4  16
21          1  15  15
22          1  12  12
23          1  10  15
24          1  11  18
25          1  17  10
26          1  14   8
27          1  16  19
28          1   9  19
29          1  14   8
30          1   7  13
31          1   6  11
32          1   4  11
33          1   4  14
34          1   8  17
35          1  13   3
36          1   9   2
37          1  18   4
38          1  10   5
39          1   4   7
40          1  18  13
41          1   1  11
42          1   7   5
43          1  13   9
44          1  14   2
45          1   1  10
46          1  18  12
47          1   4  15
48          1   9   4
49          1  17  11

In [8]:
w=np.zeros(x.shape[1])
w
#x.shape[1]

array([0., 0., 0.])

In [9]:
def myprediction(features,weights):

    predictions=np.dot(features,weights)
    return(predictions)

myprediction(x,w)
#myprediction(x,np.ones(x.shape[1]))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
def myerror(target,features,weights):
    error=target-myprediction(features,weights)
    return(error)

In [11]:
def mycost(target,features,weights):
    error=myerror(target,features,weights)
    cost=np.dot(error.T,error)
    return(cost)

mycost(y,x,w)

33508.65433234242

In [12]:
def gradient(target,features,weights):
    
    error=myerror(target,features,weights)
    
    gradient=-np.dot(features.T,error)
    
    return(gradient)

gradient(y,x,w)

array([  740.829584  ,  5984.797173  , 12024.71794376])

In [16]:
def my_lr(target,features,learning_rate):
    
    weights=np.zeros(features.shape[1])
    pcf = mycost(target,features,weights)
    for i in np.arange(100000):
        weights -= learning_rate*gradient(target,features,weights)
        weights[0] -=30*learning_rate*gradient(target,features,weights)[0] # if you comment this out , your coefficient estimates will not be as good as sklearn, why?
        
        ncf = mycost(target,features,weights)
        if abs(ncf-pcf) < 0.00001:
            break
        if i%100==0:
            print(i,pcf,ncf,weights)
        pcf = ncf
    return(weights)

my_lr(y,x,0.0000001)

0 33508.65433234242 33469.196912381994 [-0.00229382 -0.00059848 -0.00120247]
100 29991.270332598575 29960.099446826953 [-0.2162806  -0.05473497 -0.1157603 ]
200 27203.385590811293 27178.58390604291 [-0.40235967 -0.09854382 -0.21997461]
300 24976.430787513396 24956.52887292635 [-0.5640151  -0.13335224 -0.31509256]
400 23181.210707137376 23165.08230754733 [-0.70429649 -0.16032152 -0.40220629]
500 21718.698049412298 21705.47984736375 [-0.82587315 -0.1804677  -0.48227219]
600 20512.9799713617 20502.01011163911 [-0.93108151 -0.19467973 -0.55612787]
700 19505.853971378012 19496.624960585512 [-1.02196663 -0.20373527 -0.62450692]
800 18652.687437921115 18644.810057706134 [-1.10031854 -0.20831463 -0.68805194]
900 17919.24537120378 17912.421029726935 [-1.16770405 -0.20901287 -0.7473258 ]
1000 17279.259883222898 17273.25943170068 [-1.22549454 -0.20635044 -0.80282164]
1100 16712.568021026324 16707.21552357484 [-1.27489039 -0.20078249 -0.85497153]
1200 16203.685018392207 16198.845316908964 [-1.3169

array([ 2.41561938,  2.04702496, -3.95139654])

In [15]:
t=4
t-=3
t

1

In [17]:
my_lr(y,x,0.1)

0 33508.65433234242 373030427942875.3 [ 2.74966012e+06 -5.98479717e+02 -1.20247179e+03]
100 nan nan [nan nan nan]
200 nan nan [nan nan nan]
300 nan nan [nan nan nan]


/Users/ed/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.
/Users/ed/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:7: RuntimeWarning: invalid value encountered in double_scalars
  import sys


400 nan nan [nan nan nan]
500 nan nan [nan nan nan]
600 nan nan [nan nan nan]
700 nan nan [nan nan nan]
800 nan nan [nan nan nan]
900 nan nan [nan nan nan]
1000 nan nan [nan nan nan]
1100 nan nan [nan nan nan]
1200 nan nan [nan nan nan]
1300 nan nan [nan nan nan]
1400 nan nan [nan nan nan]
1500 nan nan [nan nan nan]
1600 nan nan [nan nan nan]
1700 nan nan [nan nan nan]
1800 nan nan [nan nan nan]
1900 nan nan [nan nan nan]
2000 nan nan [nan nan nan]
2100 nan nan [nan nan nan]
2200 nan nan [nan nan nan]
2300 nan nan [nan nan nan]
2400 nan nan [nan nan nan]
2500 nan nan [nan nan nan]
2600 nan nan [nan nan nan]
2700 nan nan [nan nan nan]
2800 nan nan [nan nan nan]
2900 nan nan [nan nan nan]
3000 nan nan [nan nan nan]
3100 nan nan [nan nan nan]
3200 nan nan [nan nan nan]
3300 nan nan [nan nan nan]
3400 nan nan [nan nan nan]
3500 nan nan [nan nan nan]
3600 nan nan [nan nan nan]
3700 nan nan [nan nan nan]
3800 nan nan [nan nan nan]
3900 nan nan [nan nan nan]
4000 nan nan [nan nan nan]
4100 na

array([nan, nan, nan])

In [18]:
from sklearn.linear_model import LinearRegression

In [19]:
lr=LinearRegression()

In [20]:
x.shape

(50, 3)

In [21]:
lr.fit(x.iloc[:,1:],y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
lr.coef_

array([ 1.99886071, -3.99415917])

In [23]:
lr.intercept_

3.457706177172133